version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fitstore
      MYSQL_USER: fituser
      MYSQL_PASSWORD: fitpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fitstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: fituser
      SPRING_DATASOURCE_PASSWORD: fitpassword
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./tpo-frontend
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
