spring:
  application:
    name: TPOGrupo10

  datasource:
    url: jdbc:mysql://localhost:3306/fitstore?useSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update

firebase:
  credentials:
    path: classpath:fitstore-tpo-firebase-adminsdk-fbsvc-a011839fe3.json
  bucket: fitstore-tpo.firebasestorage.app

server:
  servlet:
    context-path: /fitstore-api/v1