spring:
  application:
    name: TPOGrupo10
  datasource:
    url: jdbc:mysql://mysql:3306/fitstore
    username: root
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

web:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:5173"
      - "http://127.0.0.1:3000"
      - "http://127.0.0.1:5173"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers:
      - "*"
    exposed-headers:
      - "Authorization"
    allow-credentials: true
    max-age: 3600

firebase:
  credentials:
    path: classpath:fitstore-tpo-firebase-adminsdk-fbsvc-f765dc5523.json
  bucket: fitstore-tpo.firebasestorage.app

server:
  servlet:
    context-path: /fitstore-api/v1

jwt:
  secret: unaClaveSecretaConAlMenos32Caracteres!!